name: CI/CD - Angular Docker K8s

on:
  push:
    branches: ["main"]

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install Dependencies
      run: npm ci

    - name: Build Angular Production
      run: npm run build -- --configuration=production

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker Image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/angular-app:latest .

    - name: Push Docker Image
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/angular-app:latest

    # ---- Kubernetes Deployment ----

    # - name: Install kubectl
    #  run: |
    #    curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
    #    chmod +x kubectl
    #    sudo mv kubectl /usr/local/bin/

    - name: Setup kubeconfig
      run: |
        echo "${{ secrets.KUBE_CONFIG }}" | base64 --decode > kubeconfig
      shell: bash

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f angular-deployment.yaml --validate=false --kubeconfig=kubeconfig
        kubectl set image deployment/angular-app angular-container=${{ secrets.DOCKER_USERNAME }}/angular-app:latest --kubeconfig=kubeconfig
        kubectl rollout restart deployment/angular-app --kubeconfig=kubeconfig
